"""Create direction tables

Revision ID: 5c5299fa248d
Revises: 81f301c5d20c
Create Date: 2026-06-28 13:44:17.754938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5c5299fa248d"
down_revision: Union[str, Sequence[str], None] = "81f301c5d20c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "direction",
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_username", sa.String(length=64), nullable=False),
        sa.Column("requires_screening", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("telegram_chat_id", name=op.f("pk_direction")),
    )
    op.create_index(
        op.f("ix_direction_telegram_chat_id"),
        "direction",
        ["telegram_chat_id"],
        unique=False,
    )
    op.create_table(
        "user_direction_access",
        sa.Column(
            "user_direction_access_id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "screening_status",
            sa.Enum("NOT_STARTED", "APPROVED", name="screeningstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["telegram_chat_id"],
            ["direction.telegram_chat_id"],
            name=op.f("fk_user_direction_access_telegram_chat_id_direction"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
            name=op.f("fk_user_direction_access_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_direction_access_id", name=op.f("pk_user_direction_access")
        ),
    )
    op.create_index(
        op.f("ix_user_direction_access_telegram_chat_id"),
        "user_direction_access",
        ["telegram_chat_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_direction_access_telegram_chat_id"),
        table_name="user_direction_access",
    )
    op.drop_table("user_direction_access")
    op.drop_index(
        op.f("ix_direction_telegram_chat_id"), table_name="direction"
    )
    op.drop_table("direction")
    # ### end Alembic commands ###
