"""initial schema

Revision ID: 278d0d4c9125
Revises: 
Create Date: 2026-10-05 18:47:28.083652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '278d0d4c9125'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate doesn't emit extensions; the GIN trigram index on tags.title needs this one.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ban_reason', sa.String(length=1024), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_roles_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('category_id', 'slug', name=op.f('uq_roles_category_id'))
    )
    op.create_index(op.f('ix_roles_category_id'), 'roles', ['category_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('normalized_title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('approved', 'pending', 'rejected', name='tag_status'), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_tags_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('normalized_title', name=op.f('uq_tags_normalized_title'))
    )
    op.create_index('ix_tags_title_trgm', 'tags', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('role_fields',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('select', 'multi_select', 'number', 'text', 'boolean', name='role_field_type'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_filterable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_fields_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_fields')),
    sa.UniqueConstraint('role_id', 'key', name=op.f('uq_role_fields_role_id'))
    )
    op.create_index(op.f('ix_role_fields_role_id'), 'role_fields', ['role_id'], unique=False)
    op.create_table('tag_scopes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_tag_scopes_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_tag_scopes_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tag_scopes_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag_scopes')),
    sa.UniqueConstraint('tag_id', 'category_id', 'role_id', name=op.f('uq_tag_scopes_tag_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_tag_scopes_category_id_role_id', 'tag_scopes', ['category_id', 'role_id'], unique=False)
    op.create_index(op.f('ix_tag_scopes_tag_id'), 'tag_scopes', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_scopes_tag_id'), table_name='tag_scopes')
    op.drop_index('ix_tag_scopes_category_id_role_id', table_name='tag_scopes')
    op.drop_table('tag_scopes')
    op.drop_index(op.f('ix_role_fields_role_id'), table_name='role_fields')
    op.drop_table('role_fields')
    op.drop_index('ix_tags_title_trgm', table_name='tags', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_table('tags')
    op.drop_index(op.f('ix_roles_category_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###

    # drop_table leaves PG enum types behind, which would make the next upgrade fail.
    # pg_trgm is deliberately kept: it is a shared extension, not owned by this revision.
    op.execute("DROP TYPE role_field_type")
    op.execute("DROP TYPE tag_status")
