"""profiles

Revision ID: ca773380d102
Revises: 278d0d4c9125
Create Date: 2026-10-06 21:20:10.449529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca773380d102'
down_revision: Union[str, Sequence[str], None] = '278d0d4c9125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('goals_description', sa.Text(), nullable=False),
    sa.Column('extra_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'hidden_by_admin', name='profile_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_profiles_category_id_categories')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_profiles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', 'category_id', 'role_id', name=op.f('uq_profiles_user_id'))
    )
    op.create_index('ix_profiles_category_id_role_id_status', 'profiles', ['category_id', 'role_id', 'status'], unique=False)
    op.create_index('ix_profiles_extra_attributes', 'profiles', ['extra_attributes'], unique=False, postgresql_using='gin')
    op.create_table('profile_tags',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_tags_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_profile_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'tag_id', name=op.f('pk_profile_tags'))
    )
    op.create_index(op.f('ix_profile_tags_tag_id'), 'profile_tags', ['tag_id'], unique=False)
    # users.active_profile_id has been a plain column since the initial revision. users and profiles reference each
    # other, so this foreign key can only be added after both tables exist.
    op.create_foreign_key(op.f('fk_users_active_profile_id_profiles'), 'users', 'profiles', ['active_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_active_profile_id_profiles'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_profile_tags_tag_id'), table_name='profile_tags')
    op.drop_table('profile_tags')
    op.drop_index('ix_profiles_extra_attributes', table_name='profiles', postgresql_using='gin')
    op.drop_index('ix_profiles_category_id_role_id_status', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###

    # drop_table leaves PG enum types behind, which would make the next upgrade fail.
    op.execute("DROP TYPE profile_status")
